[package]
name = "Cryo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
ffsend-api = {version = "0.7.3", features = ["send3"]}
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
url = "2"
terminal-menu = "3.0.0"